### ISSUE TITLE
Slicer remains still while trying to convert the dicoms to nifti

### ISSUE THREAD

**Issue by Hoda1394** [KCL-BMEIS/VS_Seg#8]
I am following the instructions in the preprocessing folder to convert the data to Nifti but it does not work. I am using slicer 5.2.2 on mac os. and the slicer remains still and does nothing after giving these outputs,
```
Switch to module:  "Welcome"
['1']
case: 1
> <string>(440)main()
```
any idea what maybe wrong?

**Comment by aaronkujawa** [comment]
Hi, 
Sorry, I don't know what went wrong. I just tested it again on Slicer5.2.1. What is the full command you run? The input-path is the output from the previous script, [TCIA_data_convert_into_convenient_folder_structure.py](https://github.com/KCL-BMEIS/VS_Seg/blob/master/preprocessing/TCIA_data_convert_into_convenient_folder_structure.py) ?

**Comment by Hoda1394** [comment]
Hi, 
Thanks for the reply. yes, the input path is the output of the `TCIA_data_convert_into_convenient_folder_structure.py`. I am going to try to remove everything and try it again from the beginning. Hope it will work.
